pyproject.toml
ruyi/cli/__init__.py
ruyi/cli/prereqs.py
ruyi/cli/user_input.py
ruyi/device/provision_cli.py
ruyi/ruyipkg/pkg_cli.py
ruyi/ruyipkg/unpack.py

Device provisioner

---

ruyi/device/provision_cli.py

And fix the missing check for sudo.
Fixes: #39

Wrap fastboot calls with sudo

---

ruyi/cli/self_cli.py

fix(cli): remove the state root on purging self

---

ruyi/device/provision_cli.py

feat(provision): add support for four new boards

---

README.md
ruyi/config/__init__.py

Allow configuring repo settings via config files

---

docs/repo-structure.md
ruyi/device/provision_cli.py
ruyi/ruyipkg/pkg_manifest.py
scripts/dist-inner.py

Support provisioning live media

---

ruyi/utils/ssl_patch.py

[0.7.x] Prioritize distro-specific certificate paths

---

docs/repo-structure.md
pyproject.toml
ruyi/ruyipkg/pkg_cli.py
ruyi/ruyipkg/pkg_manifest.py
ruyi/ruyipkg/repo.py

Repo format upgrade

---

poetry.lock
pyproject.toml
ruyi/__init__.py
ruyi/__main__.py
ruyi/cli/__init__.py
ruyi/device/provision_cli.py

Refuse to run as root without consent & only do sudo in provisioner when required

---

docs/repo-structure.md
ruyi/ruyipkg/unpack.py
ruyi/ruyipkg/unpack_method.py

This is necessary for several upcoming board images.

Support LZ4 compression

---

docs/programmatic-usage.md
ruyi/ruyipkg/pkg_cli.py

[0.10.x] Fix inadvertent regression of `ruyi list` output

---

ruyi/utils/xdg_basedir.py

fix: fix copy-pasta in XDG state directory handling

---

pyproject.toml
ruyi/ruyipkg/unpack.py

Fixes: #170
(cherry picked from #171)

[0.14.x] fix incorrectly placed type assertion

---

ruyi/ruyipkg/unpack.py

fix incorrectly placed type assertion

---

ruyi/cli/__init__.py
ruyi/ruyipkg/admin_cli.py
ruyi/ruyipkg/atom.py
ruyi/ruyipkg/canonical_dump.py
ruyi/ruyipkg/pkg_cli.py
ruyi/ruyipkg/pkg_manifest.py
ruyi/ruyipkg/repo.py
ruyi/utils/toml.py

This allows deprecating the `v0` JSON package manifest format in the future.

Support upgrading and formatting package manifests

---

ruyi/cli/self_cli.py
ruyi/telemetry/store.py

Do not re-create directories after purging all state

---

ruyi/mux/runtime.py

Fix proxying to unprefixed clang

---

poetry.lock
pyproject.toml

Add missing typing_extensions dep

---

ruyi/cli/self_cli.py

Turned out the local control flow was tricky enough to warrant some code motion.
Fixes: #226

Really fix telemetry data removal when purging self

---

ruyi/__main__.py
ruyi/telemetry/node_info.py
ruyi/utils/ci.py

Test suite may need adjustment; cc @weilinfox

Allow running `ruyi` as root in CI

---

.github/workflows/pr.yml
poetry.lock
pyproject.toml
ruyi/device/provision_cli.py
ruyi/mux/venv/provision.py
ruyi/ruyipkg/pkg_manifest.py
ruyi/ruyipkg/repo.py
ruyi/telemetry/node_info.py
ruyi/utils/ci.py
ruyi/utils/porcelain.py
ruyi/version.py

For a clean VSCode editing experience (any typing error there will also get caught in CI).

Fix Pyright issues and run it in CI

---

ruyi/telemetry/store.py
ruyi/telemetry/telemetry_cli.py

By reusing the consent notice logic.

Implement verbose output of telemetry status

---

.github/workflows/pr.yml

See: https://github.com/actions/runner-images/issues/10636

Ensure Ubuntu 22.04 for the baseline-deps CI job

---

.github/workflows/pr.yml
poetry.lock
pyproject.toml
scripts/install-baseline-deps.sh
tests/fixtures/__init__.py

Make the test suite compatible with pytest 6.2.5+
