ruyi/ruyipkg/checksum.py
ruyi/ruyipkg/distfile.py

feat(ruyipkg): provide troubleshooting aid in case of fetch failures

---

ruyi/__main__.py

Fix python missing on some distros

---

ruyi/ruyipkg/news_cli.py
ruyi/utils/markdown.py

see https://github.com/Textualize/rich/issues/2137

Render news items with slim headings

---

ruyi/utils/ssl_patch.py

It has been reported that openEuler has /etc/ssl/certs but not /etc/ssl/cert.pem, leading to certificate check failures later when connecting to github.com. Its /etc/pki/tls works fine though, so let's probe the distro-specific path before the generic one, so this distro can (finally) work.

Prioritize distro-specific certificate paths

---

ruyi/device/provision_cli.py

Fixes #109 together with https://github.com/ruyisdk/packages-index/commit/fab560c207ee9c54ad29a9c074ab0ec8a2a2bea4

Streamline no-op device provision combos

---

ruyi/ruyipkg/unpack.py

Make the unpacking operation atomic

---

ruyi/ruyipkg/pkg_manifest.py

It was done in the wrong direction.
Fixes: a7d5190 ("feat(ruyipkg): define v1 package format")
Fixes: #126

fix compatibility handling of the `kind` field

---

ruyi/ruyipkg/pkg_cli.py
ruyi/ruyipkg/unpack.py

Fix unpacking failure involving packages with multiple distfiles

---

ruyi/__init__.py
ruyi/__main__.py
ruyi/utils/nuitka.py
scripts/dist.sh
scripts/patches/nuitka/0001-Onefile-Preserve-the-original-argv-0-in-__compiled__.patch

Backport of #189 to the v0.17.x release branch.

[0.17.x] Fix mux operation with Nuitka 2.4

---

ruyi/ruyipkg/repo.py

当运行 `ruyi news list` 命令时，没有在 `open()` 命令中指定 `encoding`，当读出来的内容中包含 `Unicode` 字符时，会导致 `ruyi` 抛出 `UnicodeDecodeError` 的异常：
```shell
Traceback (most recent call last):
File "/home/reki/.cache/ruyi/progcache/0.16.0/x86_64/__main__.py", line 53, in <module>
File "/home/reki/.cache/ruyi/progcache/0.16.0/x86_64/ruyi/cli/__init__.py", line 319, in main
File "/home/reki/.cache/ruyi/progcache/0.16.0/x86_64/ruyi/ruyipkg/news_cli.py", line 42, in cli_news_list
File "/home/reki/.cache/ruyi/progcache/0.16.0/x86_64/ruyi/ruyipkg/repo.py", line 462, in news_store
File "/home/reki/.cache/ruyi/progcache/0.16.0/x86_64/ruyi/ruyipkg/repo.py", line 454, in ensure_news_cache
File "encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 25: ordinal not in …
```

fix: exception when news contains UTF-8 character

---

ruyi/config/news.py
ruyi/mux/venv/__main__.py
ruyi/ruyipkg/admin_cli.py
ruyi/ruyipkg/repo.py
scripts/dist-inner.py

In cases where `LC_CTYPE` and `LANG` are invalid, the default I/O encoding for text files will become `ascii` if we're running from a Nuitka dist. While the user's configuration is likely very broken by having invalid locale settings, it's probably inappropriate to assume UTF-8 output, even though we mostly only care about that. However, simply making sure that every text file is opened with encoding explicitly set to `utf-8` can do for the time being.
Fixes: #185

fix: explicitly specify utf-8 for text file I/O

---

ruyi/cli/__init__.py
ruyi/cli/self_cli.py
ruyi/cli/version_cli.py
ruyi/config/__init__.py
ruyi/device/provision_cli.py
ruyi/mux/venv/venv_cli.py
ruyi/ruyipkg/news_cli.py
ruyi/ruyipkg/pkg_cli.py
ruyi/ruyipkg/profile_cli.py
ruyi/ruyipkg/update_cli.py

Distro packagers are encouraged to place the following content in `$PREFIX/share/ruyi/config.toml` (`$PREFIX` is usually `/usr`):
```toml
[installation]
externally_managed = true  # by the system package manager
```
To ensure `ruyi` knows that it's managed by an external entity. This can prevent accidental self-uninstallation if the official Nuitka build of `ruyi` is packaged, for example.

Better support externally-managed installations

---

ruyi/cli/builtin_commands.py
ruyi/cli/cmd.py
ruyi/pluginhost/__init__.py
ruyi/pluginhost/api.py
ruyi/pluginhost/paths.py
ruyi/pluginhost/plugin_cli.py
ruyi/pluginhost/unsandboxed.py
ruyi/ruyipkg/admin_cli.py
ruyi/ruyipkg/repo.py
tests/fixtures/__init__.py
tests/fixtures/plugins_suites/with_/foo/mod.star
tests/pluginhost/test_api.py

In an experiment to allow more logic to reside outside of `ruyi` proper, for increasing development agility even more.
This is not currently meant to be stable; exact UX (or even presence) of the feature is not guaranteed for now.

Support plugin-provided Ruyi subcommands

---

.github/workflows/pr.yml
README.md
poetry.lock
pyproject.toml
ruyi/config/__init__.py
ruyi/mux/venv/emulator_cfg.py
ruyi/pluginhost/__init__.py
ruyi/pluginhost/api.py
ruyi/pluginhost/unsandboxed.py
ruyi/ruyipkg/pkg_cli.py
ruyi/ruyipkg/pkg_manifest.py
ruyi/ruyipkg/provisioner.py
ruyi/ruyipkg/repo.py
ruyi/ruyipkg/unpack_method.py
ruyi/telemetry/node_info.py
ruyi/utils/git.py
ruyi/utils/porcelain.py
scripts/build-pygit2.py
scripts/dist-inner.py
scripts/organize-release-artifacts.py
tests/fixtures/__init__.py

Part of #229. Should have no user-visible impact.

Lower Python version requirement to 3.10

---

poetry.lock
pyproject.toml
ruyi/config/errors.py
ruyi/config/schema.py
ruyi/telemetry/telemetry_cli.py
tests/config/test_schema.py

* ensure `ruyi`-recorded config datetimes are timezone-aware
* make `ruyi telemetry consent` write the consent time including the current local time zone

Make `ruyi` config datetimes timezone-aware

---

scripts/make-reproducible-source-tarball.sh

We intend our source tarballs to have the same layout as the GitHub-generated ones, but one nesting level was missing previously.

Fix directory layout of source tarballs

---

scripts/gen_matrix.py

Availability for public repositories has been in public beta for a little while. This should help reduce our maintenance burden, if not also for the build times.
See: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

Run arm64 dist jobs on GHA public runners

---

.github/workflows/dist.yml

This was forgotten during the last bump for Linux.

Bump Python to 3.13 for Windows builds too

---

ruyi/device/provision_cli.py

Many users reported difficulties with the word "provision", and suggested "flash" as an alternative. While what we do is expected to be more than just "flashing" at least in the roadmap, it is the case for now, and "flash" is easier for non-English speakers. So just add an alias to reduce typing and confusion for those.
Link: https://ruyisdk.cn/t/topic/506

Add alias `ruyi device flash` for `ruyi device provision`

---

packaging/completions/bash
packaging/completions/zsh

For distros to integrate the feature more easily.

Bundle CLI completion loader script in source tarballs

---

scripts/dist-gha.sh
scripts/dist.sh

And install cffi from the index too to save time.
For now the cffi build is taken from the https://gitlab.com/riseproject/python/wheel_builder project.

Speed up riscv64 dist builds

---

ruyi/ruyipkg/repo.py

We can alert the user of possible connectivity issues if the sync doesn't finish after a while, but telling the user syncing is in progress is going to help.
Fixes: #352

Tell the user repo update is in progress before syncing
